@startuml
scale 600 width
state "on" as on  {
    state "loud" as loud  {
    }
    state "quiet" as quiet  {
        state "quiet b" as quiet_b  {
        }
        state "quiet a" as quiet_a #LightGreen {
        }
    }
}
state "off" as off  {
}
loud --> quiet : volume_down
quiet --> loud : volume_up
on --> off : switched_off
off --> on : switched_on
 
@enduml
