@startuml
state "b" as b  {
    state "b.b" as b.b  {
    }
    state "b.a" as b.a  {
        state "b.a.b" as b.a.b  {
        }
        state "b.a.a" as b.a.a #LightGreen {
        }
    }
}
state "a" as a  {
}
b.b --> b.a : b.b_to_b.a
b.a.a --> a : b.a.a_to_a
b.a --> b.b : b.a_to_b.b
b --> a : b_to_a
a --> b : a_to_b
a --> b.a.b : a_to_b.a.b
 
@enduml
